<template>
  <div>
    switch 组件
    <p>switch 的文档</p>
    <p>switch 的文档</p>
    <p>switch 的文档</p>
    <p>switch 的文档</p>
    <p>switch 的文档</p>
    <p>switch 的文档</p>
    <p>switch 的文档</p>
    <p>switch 的文档</p>
    <p>switch 的文档</p>
    <p>switch 的文档</p>
    <p>switch 的文档</p>
    <p>switch 的文档</p>
    <p>switch 的文档</p>
    <p>switch 的文档</p>
    <p>switch 的文档</p>
    <p>switch 的文档</p>
    <p>switch 的文档</p>
    <p>switch 的文档</p>
    <p>switch 的文档</p>
    <p>switch 的文档</p>
    <p>switch 的文档</p>
    <p>switch 的文档</p>
    <p>switch 的文档</p>
    <p>switch 的文档</p>
    <p>switch 的文档</p>
    <p>switch 的文档</p>
    <p>switch 的文档</p>
    <p>switch 的文档</p>
    <p>switch 的文档</p>
    <p>switch 的文档</p>
    <p>switch 的文档</p>
    <p>switch 的文档</p>
    <p>switch 的文档</p>
    <p>switch 的文档</p>
    <p>switch 的文档</p>
    <p>switch 的文档</p>
    <p>switch 的文档</p>
    <p>switch 的文档</p>
    <p>switch 的文档</p>
    <p>switch 的文档</p>
    <p>switch 的文档</p>
    <p>switch 的文档</p>
    <p>switch 的文档</p>
    <p>switch 的文档</p>
    <p>switch 的文档</p>
    <p>switch 的文档</p>
    <p>switch 的文档</p>
    <p>switch 的文档</p>
    <p>switch 的文档</p>
    <p>switch 的文档</p>
    <p>switch 的文档</p>
    <p>switch 的文档</p>
    <p>switch 的文档</p>
    <p>switch 的文档</p>
    <p>switch 的文档</p>
    <p>switch 的文档</p>
    <p>switch 的文档</p>
    <p>switch 的文档</p>
    <p>switch 的文档</p>
    <p>switch 的文档</p>
    <p>switch 的文档</p>
    <p>switch 的文档</p>
    <p>switch 的文档</p>
  </div>
</template>